# fly.toml app configuration file generated for eggincutils on 2026-02-26T17:29:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eggincutils'
primary_region = 'iad'
swap_size_mb = 512

[env]
  # Point your app to the persistent volume path
  LOOT_DATA_CACHE_FILE = "/data/eggincutils-loot-cache.json"
  # Keep Node memory in check for the 512MB RAM tier
  NODE_OPTIONS = "--max-old-space-size=768"
  NEXT_PUBLIC_SITE_URL = "https://HensIn.space"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "my_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
