[[redirects]]
from = "/xp-ge-craft"
to = "/xp-ge-craft/"
status = 301

[[redirects]]
from = "/xp-ge-craft/*"
to = "https://xp-ge-craft.netlify.app/xp-ge-craft/:splat"
status = 200

[[redirects]]
from = "/ship-timer/*"
to = "https://ship-timer.netlify.app/:splat"
status = 200
